auth:
  kind: "fake"
  spec:
    redirect_url: "https://example.com/oauth_callback"
    app_id: "cli_xxxxxxx"
    app_secret: "xxxxxxxx"
pipes:
  - port: 8070
    access:
      - host_name: 'git.example.com'
        groups:
          - developer
    session:
      cookie_key: "__test__"
      cookie_domain: ".example.com"
      expires_in: 3600
      hash_key: "12345612345678901234561234567890"
      block_key: "1234561234567890"
    backend:
      host: "127.0.0.1"
      port: 8000
      timeout: 5000